server:
  port: 8087
spring:
  application:
    name: ad-search
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/ad_cloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8}
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    password: 123456
    jedis:
      pool:
        max-wait: -1ms
        max-active: 8
        min-idle: 5
        time-between-eviction-runs: 6000ms
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka
  instance:
    instance-id: adsearch8087
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:org/mantou/ad/mapper/*.xml
  type-aliases-package: org.mantou.ad.model,org.mantou.ad.dto
